---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos65
    driver:
      box: box-cutter/centos65
      box_url: box-cutter/centos65

suites:
  - name: server
    run_list:
      - recipe[perforce::p4d]
    attributes:
